import = [
  "~/.config/alacritty/tokyonight-storm.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Semicolon"
mods = "Alt"

[mouse]
hide_when_typing = true

[window]
dynamic_title = true
opacity = 0.88
title = "Terminal"

[window.class]
instance = "Alacritty Instance"

[window.dimensions]
columns = 105
lines = 24
