[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Semicolon"
mods = "Alt"

[mouse]
hide_when_typing = true

[window]
dynamic_title = true
opacity = 0.88
title = "Terminal"

[window.class]
instance = "Alacritty Instance"

[window.dimensions]
columns = 105
lines = 24
