#!/usr/bin/env bash

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

[[ -f "$HOME/.deno/env" ]] && source "$HOME/.deno/env"

export PATH=$PATH:$HOME/.local/bin

PYENV_ROOT="$HOME/.pyenv"
if [[ -d "$PYENV_ROOT" ]]; then
  export PYENV_ROOT
  export PATH=$PATH:$PYENV_ROOT/bin
  # path=("$path" "$PYENV_ROOT/bin")
fi

RBENV_ROOT="$HOME/.rbenv"
if [[ -d "$RBENV_ROOT" ]]; then
  export RBENV_ROOT
  export PATH=$PATH:$RBENV_ROOT/bin
  # path=("$path" "$RBENV_ROOT/bin")
fi
