# Oh My Zsh install directory
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="sorin"
ZSH_THEME="spaceship"
export SPACESHIP_PROMPT_ADD_NEWLINE=false
export SPACESHIP_PROMPT_SEPARATE_LINE=true

export SPACESHIP_CHAR_SYMBOL=" "
export SPACESHIP_CHAR_SYMBOL_SECONDARY=" "

zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="dd.mm.yyyy"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  colored-man-pages
)

fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"

# Vars
export DEV_DIR="$HOME/Dev"

# Path
export PYENV_ROOT="$HOME/.pyenv"
export RBENV_ROOT="$HOME/.rbenv"

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export DENO_INSTALL="/home/fell/.deno"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=/usr/bin:$PATH:/opt/firefox:$HOME/AppImages:$HOME/.local/bin:$RBENV_ROOT/bin:$PYENV_ROOT/bin:$DENO_INSTALL/bin

export NVIM_DIR="$HOME/.config/nvim"
export NVIMRC="$NVIM_DIR/init.lua"
export NVIM_PLUGINS="$NVIM_DIR/lua/plugins.lua"

export VIMRC="$HOME/.vimrc"
export ZSHRC="$HOME/.zshrc"
export TERMRC="$HOME/.alacritty.yml"

export DOTNET_CLI_UI_LANGUAGE=en
export BAT_THEME="OneHalfDark"

eval "$(rbenv init - zsh)"
eval "$(pyenv init -)"

export PYTHON_EXECUTABLE=$(which python3)

# Alias
alias py='python3'

alias dev="cd $DEV_DIR"

alias clip='xclip -selection clipboard'

alias nv='nvim'

# Funcs
changeJavaHome() {
  if [ $JAVA_HOME = "/usr/lib/jvm/java-8-openjdk" ]; then
    export JAVA_HOME="/usr/lib/jvm/jdk-17.0.5"
  else
    export JAVA_HOME="/usr/lib/jvm/java-8-openjdk"
  fi
  export PATH=$JAVA_HOME/bin:$PATH
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
