#!/usr/bin/env zsh

# Vars
export ZSH="$HOME/.zsh"
export ZSHRC="$HOME/.zshrc"

export DOTFILES_ROOT="$HOME/.dotfiles"

export EDITOR="nvim"

export DEV_DIR="$HOME/Dev"

export NVIM_DIR="$HOME/.config/nvim"
export NVIMRC="$NVIM_DIR/init.lua"

export PYTHON_EXECUTABLE=$(which python3)

export DOTNET_CLI_UI_LANGUAGE=en

# Plugins
ZSH_SYNTAX_DIR="$ZSH/zsh-syntax-highlighting"
if [[ -d "$ZSH_SYNTAX_DIR" ]]; then
  source "$ZSH_SYNTAX_DIR/zsh-syntax-highlighting.zsh"
else
  echo "Warning: the zsh-syntax-highlighting plugin is not installed."
fi

ZSH_SUGGESTIONS_DIR="$ZSH/zsh-autosuggestions"
if [[ -d "$ZSH_SUGGESTIONS_DIR" ]]; then
  source "$ZSH_SUGGESTIONS_DIR/zsh-autosuggestions.zsh"
else
  echo "Warning: the zsh-autosuggestions plugin is not installed."
fi

# Prompt
SPACESHIP_PROMPT_DIR="$ZSH/spaceship"
if [[ -d "$SPACESHIP_PROMPT_DIR" ]]; then
  export SPACESHIP_PROMPT_ADD_NEWLINE=false
  export SPACESHIP_PROMPT_SEPARATE_LINE=true
  export SPACESHIP_CHAR_SYMBOL=" "
  export SPACESHIP_CHAR_SYMBOL_SECONDARY=" "
  export SPACESHIP_RUBY_SYMBOL="󰴭 "

  source "$SPACESHIP_PROMPT_DIR/spaceship.zsh"
else
  echo "Warning: the spaceship-prompt is not installed."
fi

# Alias
alias py='python3'

alias dev="cd \$DEV_DIR"

alias clip='xclip -selection clipboard'

alias nv='nvim'

alias ls='ls --color=tty --group-directories-first'

# Functions
light_mode() {
  sed -i -e "s/zenbones_dark/catppuccin-latte/g" "$HOME/.config/alacritty/alacritty.toml"
}

dark_mode() {
  sed -i -e "s/catppuccin-latte/zenbones_dark/g" "$HOME/.config/alacritty/alacritty.toml"
}

reload_term() {
  source "$HOME/.zshrc"
  source "$HOME/.zshenv"
}

# Others
HISTFILE="$HOME/.histfile"
HISTSIZE=1000
SAVEHIST=1000

# Final commands
for f in "$ZSH/autoload/"*; do
  source "$f"
done

[[ -s "$DOTFILES_ROOT/cli_tools/env" ]] && source "$DOTFILES_ROOT/cli_tools/env"

autoload -Uz compinit && compinit
